"""create period table

Revision ID: 083fb02d625c
Revises: 8cd8f2dfb193
Create Date: 2024-06-23 20:31:21.522892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083fb02d625c'
down_revision: Union[str, None] = '8cd8f2dfb193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('lesson', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('second_teacher_id', sa.Integer(), nullable=True),
    sa.Column('classroom', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['second_teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periods')
    # ### end Alembic commands ###
