"""create groupDay table

Revision ID: 393284cf47da
Revises: da7227bcb04b
Create Date: 2024-06-23 21:41:37.828748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393284cf47da'
down_revision: Union[str, None] = 'da7227bcb04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupDays',
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('period_1', sa.Integer(), nullable=True),
    sa.Column('period_2', sa.Integer(), nullable=True),
    sa.Column('period_3', sa.Integer(), nullable=True),
    sa.Column('period_4', sa.Integer(), nullable=True),
    sa.Column('period_5', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['period_1'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['period_2'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['period_3'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['period_4'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['period_5'], ['periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupDays')
    # ### end Alembic commands ###
